Hayoung step1
hayeounglee/java-racingcar-1 pull request #1
Opened 2024-07-16 09:03 UTC by hayeounglee

2024-07-16 11:33 UTC, Cyma-s requested changes

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
리턴타입과 매개변수 모두 `Collection` 이 아닌 배열을 사용하셨네요!
`Collection` 과 배열은 어떤 차이점이 있을까요?

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
함수에 static 키워드를 사용하신 이유가 있을까요?

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
`Car` 배열의 이름이 `array` 로 작명되어 한 번에 어떤 이름인지 알아보기 어려울 것 같네요 🤔 변수 이름은 항상 해당 변수가 어떤 역할을 하는지 명확하게 명시해야 합니다
보다 좋은 이름은 어떤 게 있을까요?

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/Car.java
> +    int distance;
디폴트 접근 제어자로 설정하신 이유가 있을까요?

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +            if(distance-- <= 0){
if 문을 한 눈에 보고 어떤 조건인지 확인하기 어려울 것 같네요. 메서드를 분리해주세요!

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        int distance = car.distance;
직접 필드에 접근해서 데이터를 가져오는 방식은 객체 지향 프로그래밍에서 지양해야 하는 패턴입니다. `getter` 에 대해서 알아보시겠어요?

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    static void printDistance(Car car){
여기도 접근 제어자가 없는 이유가 있을까요?

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    }
메서드 사이의 공백은 의미를 나타내는 중요한 요소입니다. 메서드 사이에는 반드시 공백을 추가해주세요!

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    static boolean randomMethod() {
`randomMethod` 라는 메서드 이름은 명사입니다! 메서드 이름은 동사로 시작하도록 짓는 것이 컨벤션입니다.

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    static boolean randomMethod() {
`boolean` 을 리턴하는 메서드의 이름은 `isXXX` 로 짓는 것 또한 관행입니다.

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        int randomInt = random.nextInt(10);
`randomInt` 는 현재 프로그램에서 어떤 의미를 갖나요?

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        int randomInt = random.nextInt(10);
10 이라는 매직 넘버를 사용하게 되면 다른 개발자가 해당 코드를 보았을 때 왜 10이라는 숫자를 사용하였는지 맥락을 전혀 알 수 없습니다. 10을 상수로 분리하여 변수가 의미를 갖도록 해주세요

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        if (randomInt >= 4) {
4도 매직 넘버입니다!

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        String[] parts = input.split(",");
왜 쉼표로 분리한 String 배열의 변수 이름이 parts 일까요?

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        };
현재 프로그램에서 반드시 차가 3대만 입력된다는 보장은 어디에도 없습니다 🥲 N 개의 자동차를 처리할 수 있도록 로직을 반드시 변경해주세요

2024-07-16 11:33 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        }
마찬가지로 해당 메서드도 변경되어야겠죠?

2024-07-20 11:53 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
Collectoin : 길이 조정 가능
Array : 길이 조정 불가능(지정된 길이 값)

사용자가 처음 입력한 값(자동차 이름)을 통해 고정된 자동차 개수를 알 수 있습니다. 이로써 고정된 길이인 배열을 써도 상관없다고 생각했습니다.
그러나 한편으로는 성능 문제가 크게 차이 나지 않는 한 collection을 사용해도 좋을 것 같다는 생각이 듭니다!

2024-07-20 12:10 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
satic: class에 고정된 멤버, object애 소속된 멤버가 아님. 객체를 생성하지 않고도 static 자원에 접근이 가능.
메모리에 한번 할당되어 프로그램이 종료될 때 해제됨. 
자주 사용하게 되면 시스템 퍼포먼스에 악영향을 줌.

static을 제대로 알고 나니 필요가 없는 것 같아 삭제 했습니다.

2024-07-20 14:23 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
자동차 객체를 저장하는 역할이여서 
storeCars로 바꿔봤습니다!

2024-07-21 01:07 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +            if(distance-- <= 0){
넵! isDistanceLeft 함수를 새로 만들어서 분리해봤습니다

2024-07-21 01:10 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    }
넵 수정했습니다!

2024-07-21 01:52 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        int randomInt = random.nextInt(10);
randomInt 는 한계점을 나타냅니다 그래서 매직 넘버 THRESHOLD의 이름을 수정해봤습니닷

2024-07-21 01:53 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    static boolean randomMethod() {
isRandomNumberHigh로 수정했습니닷

2024-07-21 01:54 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        int randomInt = random.nextInt(10);
randomInt는 특정 범위에서 추출된 랜덤한 숫자 하나 입니다.

2024-07-21 01:55 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        if (randomInt >= 4) {
상수 4를 매직 넘버 THRESHOLD로 수정해봤습니닷

2024-07-21 02:13 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        String[] parts = input.split(",");
자동차의 이름을 저장하는 배열인데 명칭이 parts 보다 carNames가 더 나은 것 같아 수정했습니닷

2024-07-21 14:02 UTC, hayeounglee commented on src/main/java/Car.java
> +    int distance;
특별한 이유가 없네요... private으로 접근 제어자를 설정한 뒤 getter/setter를 이용하여 접근하도록 변경했습니다!

2024-07-21 14:07 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    static void printDistance(Car car){
이유는 없습니다 다음부터는 public/private을 빼먹지 않고 쓰는 쪽으로 해야겠습니닷

2024-07-22 06:21 UTC, Cyma-s requested changes
1차 리뷰 완료하였습니다. 다만 리뷰 과정에서 말씀드리고 싶은 부분을 발견하여, 리뷰 반영 전에 생각해보면 좋을 부분들을 먼저 안내드릴게요.

**반드시 기본 규칙을 준수해주세요**

미션을 하시면서 꼭 지켜야 하는 규칙들은 반드시 지켜진 상태로 PR 올려주셔야 중요한 부분만 리뷰할 수 있습니다. PR 제출 전 규칙을 모두 따랐는지 확인하시고 제출해주세요. 이번 리뷰에서는 규칙이 제대로 지켜지지 않은 부분들로 인해 중요한 부분을 리뷰하고 넘어가기 힘들었습니다 🥲 규칙에 대한 리뷰는 저희 둘 모두에게 시간 낭비가 될 수 있으니, 이 부분을 더 신경써주시면 감사하겠습니다.

**리뷰 과정에서 얻어가고자 하는 것은 객체지향적 사고 방식을 체화하고 이해하는 것입니다**

코드를 작성하실 때, 최대한 동작을 객체와 객체 사이의 상호작용으로 풀어낼 수 있도록 '노력해주세요'. 객체지향은 코테처럼 프로그램을 많이 만들어본다고 해서 늘지 않기 때문입니다.

만약 객체지향 프로그래밍을 어떻게 하는지 잘 모르겠다면 다른 책으로 (객체지향의 사실과 오해 추천합니다) 공부하셔도 되고요. 절대 미션 구현 과정과 코드 리뷰만으로 객체지향을 공부하고 이해할 수 있을 거라 기대하시면 안 됩니다. 그렇게 생각하면 오히려 실망하게 될 수 있어요. 미션과 리뷰는 알고 있는 지식을 다듬고, 정답 없는 문제를 같이 고민해나가는 과정이니까요.

분명 '이걸 어떻게 객체 상호작용으로 풀지?', '굳이 이 정도까지 해야 하나?' 라는 의문이 들거라는 걸 잘 압니다. 저도 그랬었습니다.

그렇지만 그런 고민 과정, 어디까지가 객체 지향이고 어디까지가 굳이인가를 알아가는 과정 자체가 중요한 것입니다. 지금까지 남은 한 달 간 미션을 진행하고 리뷰하는 과정에서 객체지향의 극한을 경험해보겠다는 각오를 해주세요. 이 부분을 너무 억지로 분리한 것 같다, 너무 이상하다 싶으면 차라리 이상한 그대로 분리하시고 코멘트를 남겨두세요. 제가 리뷰 하면서 다시 답변 드릴 수 있으니까요.

그러나 제가 느낀 지금의 구현 방식은 문제 해결에 너무 집중한 코드 같아요. 미션 목표를 달성하는 것(n개의 자동차 게임이 성공적으로 동작하게 한다)은 **당연히 만족되어야 하는 조건**이고, 그 뒤에 리팩터링을 통해 더 나은 코드(보다 읽기 쉬운 코드, 더 객체지향적인 코드)를 만들고 더 이상 고칠 부분이 없을 때 (혹은 여기서 고칠 부분을 잘 모르겠을 때) pr을 제출해야 한다는 것입니다.

이번 여름 방학의 목표를 잊지 마셔야 합니다. 단순히 프로그램을 구현하기 위해 미션을 진행하고 코드리뷰를 하는 것이 아니에요. 저희는 객체지향을 공부하려고 하는 겁니다. 
이전 코드에서는 왜 이런 리뷰를 받게 되었을까?, 왜 이 부분이 문제가 될 수 있을까?, 내가 작성하고 있는 코드는 객체지향적 코드가 맞을까? 같은 정답이 없는 문제에 대해 더 깊게 고민해보시면 좋을 것 같습니다.

무조건 미션에 시간을 많이 쏟으라는 뜻이 아닙니다. 물리적 시간이 중요한 게 아니에요. 코드에서 객체지향에 대한 고민의 흔적이 보여야 한다는 것입니다. 그래야 코드에 대한 질문이 생기고, 흥미로운 질문에 답변하는 재미를 느끼며 저희 둘 다 즐겁게 코드 리뷰하면서 성장할 수 있으니까요 :) 

너무 잔소리만 한 것 같아 미안합니다. 앞으로의 더 나은 리뷰 과정을 위해 솔직히 오지랖 같지만 한 마디 남겨봤습니다. 

혹시 리뷰 보다가 잘 이해가 안 되거나, 어떻게 해야 할 지 모르겠다고 생각되는 부분은 코멘트로 남겨주시면 답글 남기겠습니다. 감사합니다 😊

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/Car.java
> +    public Integer getDistance(){
`Integer` 로 wrapping 해준 이유는 무엇인가요?

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/Car.java
> +    public void setDistance(){
`set` 은 단순히 distance 값을 바꾸는 로직을 나타내는 이름이에요. 그렇지만 지금은 +1을 하면서 한 칸씩 전진하는 비즈니스적 의미를 가지고 있죠. 이런 비즈니스적 기능을 나타내는 이름으로 바꿔야 합니다

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
보통 Array 를 사용하는 경우는 거의 없습니다. 나중에 크기가 변동되지 않는 경우가 거의 없기 때문이죠. 여러 값을 저장할 때는 'Collection' 을 사용한다고 기억해주세요

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
왜 객체를 생성하지 않고 접근해야 할까요? RacingGame 은 어떤 역할을 하기에 객체를 생성하지 않아도 되나요?

참고) 객체를 생성하는 것이 성능에 악영향을 끼치는 건 절대 아닙니다.

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
아직 매개변수는 array로 되어 있네요? 이유가 있나요?

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    }
Distance 가 남아있지 않다는 게 무슨 뜻이죠?
Distance 가 음수인지 확인하는 것이 RacingGame 의 책임일까요?

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        String[] rank = winners.toArray(new String[winners.size()]);
여기도 아직 array 입니다~~

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +
불필요한 공백은 제거해주세요

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        Random random = new Random();
`Random` 객체는 한 번만 생성되면 될 텐데 메서드에서 반복 생성되고 있네요. 어떻게 개선할 수 있을까요?

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        if (randomInt >= THRESHOLD) {
Threshold 가 무엇을 위한 제약인지 처음 보는 개발자가 알아보기 어려울 것 같네요. 이름을 보다 비즈니스 로직을 반영할 수 있게 변경해주세요

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static boolean isRandomNumberHigh() {
반복적으로 제기되는 리뷰인데요, 현재 애플리케이션은 자동차 경주에 관한 프로그램입니다. 즉 해당 프로그램의 코드는 자동차 경주와 관련된 이름을 사용하고 코드 작동을 제대로 모르는 사람도 이해할 수 있어야 해요. 

그렇지만 isRandomNumberHigh 는 자동차 경주에 국한된 이름도 아닐 뿐더러, 그래서 랜덤 숫자가 높아서 어떤 의미를 갖는 것이지? 라는 의문을 해결해줄 수 없는 이름입니다. 

메서드 이름은 지금 코드가 작성되는 프로그램의 도메인 영역과 밀접하게 관련되어야 합니다.

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        int num = 0;
이 변수는 왜 0으로 초기화되었는지 다른 개발자는 알 수 없고, 변수 이름이 num 인 이유도 알 수 없습니다!!

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        String[] carNames = input.split(",");
String 배열은 Collection 으로 형변환해주세요. 웬만하면 배열이 코드에 남아있지 않아야 합니다.

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        num = carNames.length;
변수 재할당은 지양하는 것이 좋습니다. 해당 변수가 어디서든 값이 변경될 수 있음을 암시하기 때문이죠. 변수는 필요할 때만 생성하고, 미리 선언하지 마세요

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        Car[] storeCars = new Car[num];
store는 동사로 시작하는 느낌을 줄 수 있습니다. 변수 이름은 반드시 명사로 작명하세요

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +                maxDistance = array[i].getDistance();
들여쓰기 2이상이므로 1이하로 낮춰주세요

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +                if((isRandomNumberHigh())){storeCars[i].setDistance();}
마찬가지로 들여쓰기 2입니다

2024-07-22 06:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static void main(String[] args) {
기존 규칙에 메서드 라인의 최대 길이는 15입니다. 너무 길죠?

2024-07-22 09:30 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
Collection 사용으로 수정했습니다!

2024-07-22 09:37 UTC, hayeounglee commented on src/main/java/Car.java
> +    public Integer getDistance(){
앗 특별한 이유는 없고 Int 랑 헷갈렸습니다.

잠깐 공부해보니 Integear는 null 값 처리가 가능하다는데 
지금은 딱히 필요없는 기능 이여서 primitive type(자료형)인 Int 로 바꾸었습니다.

2024-07-22 09:41 UTC, hayeounglee commented on src/main/java/Car.java
> +    public void setDistance(){
`incrementDistance()`로 바꿨습니다

2024-07-22 09:49 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
앗지금 확인했습니다 이제는 무지성으로 collection을 써야겠네요👍

2024-07-22 09:50 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        int num = 0;
num을 삭제했습니다!

2024-07-22 10:09 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +                maxDistance = array[i].getDistance();
tab size를 1로 설정했습니다!

2024-07-25 01:50 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    }
단순한 비교 연산을 함수여서 삭제했습니닷

2024-07-25 02:24 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static void main(String[] args) {
메서드를 분리하여 라인을 줄였습니다.

2024-07-25 02:40 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static boolean isRandomNumberHigh() {
메서드 이름을 수정했습니닷

2024-07-25 02:50 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        Random random = new Random();
random 객체를 재사용할 수 있게 변경했습니닷

2024-07-25 03:25 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static String[] findMax(Car[] array){
공부한 내용) 
static: 어떤 object에 소속되는 것이 아닌, 클래스에 고정되어 있는 변수나 메서드. object를 생성하지 않고도 static 자원에 접근이 가능.
object : 일회용으로 작업을 끝내면 되는 것들은 메소드나 변수를 클래스에 소속된 그대로 사용
class: 하지만 긴 맥락을 가지고 작업해야 하는 경우에는 클래스를 직접 사용하는 것이 아니라 클래스를 복제해서 제어함

결론)
RacingCarGame이라는 class는 게임을 play하는 역할입니다. 이는 일회용 작업이므로 object를 생성이 꼭 필요하지 않다고 생각합니다.

2024-07-26 05:04 UTC, Cyma-s commented on src/main/java/Car.java
> +    public Integer getDistance(){
null 을 검사하는 위험을 없애기 위해서라도 꼭 필요한 경우가 아니라면 primitive type 을 사용하는 것이 좋습니다!

2024-07-26 05:07 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +                maxDistance = array[i].getDistance();
들여쓰기가 2 이상이라는 것은 tab size 가 2라는 뜻이 아니라 내부 로직이 얼마나 여러 개 들어있느냐를 의미합니다. 지금 코드에서는 if 문에서 들여쓰기 한 번, maxDistance 앞에 들여쓰기 한 번이 있기 때문에 두 번의 들여쓰기가 된 상태입니다. 이 부분을 메서드 분리를 통해 들여쓰기를 줄여줘야 합니다

2024-07-26 05:21 UTC, Cyma-s requested changes
이전 코드보다 메서드 / 변수 작명은 나아진 것 같네요 👍 확인해야 하는 부분을 리뷰로 남겼으니 확인해주세요 😊 아마도 다음 리뷰는 머지할 것 같습니다.

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +
공백 👀

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    private static void playGame(List<Car> carList, int tryCount){
컬렉션의 이름이 변수에 들어가는 것은 좋지 않습니다. 지금은 `List<Car>` 형태이지만, 나중에 다른 컬렉션 (set 이나 map) 으로 바뀔 수도 있기 때문에 변수 이름에 list, set, map 같은 명사가 들어가지 않는 것이 좋습니다.

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +                if((shouldMoveForward())){carList.get(i).incrementDistance();}
한 줄로 줄여쓸 수 있는 코드라도 bracket {} 은 다른 줄에 써주셔야 합니다. intellij 의 command + option + L 을 자주 눌러서 코드를 정리하는 습관을 들여주세요.

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        List<String> rank = findMax(carList);
`List<String>` rank 가 `findMax` 의 반환 값으로 반환되는 게 이상하네요. `findMax` 가 메서드 이름이라면 리턴 값은 max 값이어야 하지 않을까요?

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +            }
`String.join` 메서드를 사용해서 한 번에 쉽게 출력할 수 있습니다!

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static List<String> findMax(List<Car> array){
해당 메서드가 `public` 인 이유가 있나요?

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static List<String> findMax(List<Car> array){
여전히 매개변수 이름이 array 입니다....🥲 이전 리뷰는 다 반영했는지 확인해주세요!

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        }
들여쓰기 2 이상입니다

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static boolean shouldMoveForward() {
`should` 를 메서드 이름에 자주 사용하지는 않습니다. `isMovable` 같은 이름이 좋겠어요

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    public static void main(String[] args) {
그렇지만 여전히 15 이상입니다 🤔

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        }
이 부분도 메서드로 분리할 수 있지 않을까요? 여기 코드는 지금 어떤 역할을 수행하고 있나요?

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        int num = carNames.size();
`carNames.size()` 처럼 어느 정도 의미가 파악되는 메서드 호출은 굳이 변수로 선언하지 않으셔도 됩니다

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +            }
이 로직은 어떤 의미를 갖고 있나요? 메서드로 분리해봅시다.

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    private static void printResult(List<Car> carList){
컬렉션 이름이 포함되어 있습니다 22

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        }
그리고 이 부분도 메서드 분리할 수 있을 것 같아요.

2024-07-26 05:21 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        return winners;
`findMax` 에서 `winner` 를 리턴하고 있는 것은 메서드가 이름과 다른 행동을 하고 있는 것입니다. 메서드를 분리하거나, 아니면 지금 행동에 맞는 이름을 작명해주세요.

2024-07-27 03:53 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    private static void playGame(List<Car> carList, int tryCount){
racingCars로 수정했습니닷

2024-07-27 04:06 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        List<String> rank = findMax(carList);
getWinners로 변경했습니닷

2024-07-27 04:57 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        return winners;
메서드 이름을 변경했습니닷

2024-07-27 05:05 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        }
maxDistance를 찾는 메서드를 따로 만들어서 분리했습니다.

2024-07-27 05:18 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        }
자동차 이름별로 객체를 만드는 역할입니다.
createRacingCars 메서드로 분리했습니다.

2024-07-27 05:30 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +            }
한번 시도할때마다  racingCars의 distance를 증가할지 말지 결정합니다.
따라서 for 문을 메서드로 분리했습니다.

2024-07-27 05:33 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static void main(String[] args) {
다시 줄였습니닷

2024-07-27 05:50 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +                maxDistance = array[i].getDistance();
Math라는 class를 사용하여 1이하로 줄였봤습니닷

2024-07-27 05:53 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    public static List<String> findMax(List<Car> array){
외부 class가 사용할 일은 없으니 private으로 고쳤습니닷

2024-07-27 07:27 UTC, Cyma-s approved these changes
많이 좋아진 것 같습니다. 지금 남겨드린 리뷰는 2단계에서 반영해주세요 :) 어프루브하겠습니다.

2024-07-27 07:27 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        }
브라켓을 없앤다고 한 줄이라고 보기는 어렵고, 최대한 메서드 분리를 해보라는 취지로 들여쓰기 제한이 있다고 생각해주세용

2024-07-27 07:27 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        int listLength = racingCars.size();
굳이 필요한가요? 이전 리뷰에 있었던 내용 같습니다

2024-07-27 07:27 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +
공백 🧐

2024-07-27 07:27 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        }
요 부분도 메서드로 분리할 수 있을 것 같네요

2024-07-27 07:27 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +    private static List<String> addWinner(List<String> winners, Car car, int maxDistance){
계속해서 List 를 리턴하는 이유는 뭔가요?

2024-07-27 07:27 UTC, Cyma-s commented on src/main/java/RacingCarGame.java
> +        List<String> carNames = new ArrayList<>(Arrays.asList(input.split(",")));
`ArrayList` 로 다시 `asList` 결과를 래핑하게 되면 래핑하기 전과 어떤 것이 다를까요?

2024-07-27 08:51 UTC, merged

2024-07-30 02:49 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        }
혹시 for문 전체를 메서드로 분리한다는 말씀인가요?

2024-07-30 02:51 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +    private static List<String> addWinner(List<String> winners, Car car, int maxDistance){
리턴할 이유는 없어 해당 코드를 삭제했습니다.

2024-07-30 04:01 UTC, hayeounglee commented on src/main/java/RacingCarGame.java
> +        List<String> carNames = new ArrayList<>(Arrays.asList(input.split(",")));
ArrayList : 원소의 추가/삭제 가능, 동적크기 List
Arrays.asList() :  원소의 추가/삭제 불가능, 고정크기 List

즉 리스트를 수정하고 싶을 때 ArrayList로 다시 래핑해야 합니다.
그런데 이 경우 추후에 carNames가 추가되지는 않아 ArrayList로 래핑할 필요가 있나 하는 의문이 드네요
어떻게 생각하시나요?🤔