[2단계
hayeounglee/java-racingcar-1 pull request #2
Opened 2024-07-28 14:16 UTC by hayeounglee

![image](https://github.com/user-attachments/assets/5dc22639-d9ff-46c7-8cbc-f8158215815e)

2024-07-30 04:02 UTC, hayeounglee commented
1단계 추가 코드 리뷰도 완료했으니 
확인해주면 감사하겠습니다👍

2024-08-04 09:57 UTC, Cyma-s requested changes

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/RacingMain.java
> +
👀

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/RacingMain.java
> +        final var tryCount = InputView.getTryCount();
`var` 를 사용하신 이유가 있을까요? 어떤 장단점이 있나요?

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return racingCars;
만약 리턴된 `racingCars` 에 add, remove 를 하게 된다면 그대로 변경 사항이 반영되겠죠?
이를 막기 위해 '방어적 복사'를 할 수 있는데요, 방어적 복사란 무엇이고 왜 사용해야 하는지 댓글로 남겨주세요!

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
`scanner` 를 static 변수로 선언하신 이유가 무엇인가요?

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    public static List<String> getCarNames(){
필드와 메서드 사이에는 공백이 필요합니다

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    public static List<String> getCarNames(){
`InputView` 의 모든 메서드를 static 으로 설정해주셨는데, 이런 구조의 장단점은 무엇인가요?

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +public class InputView {
모든 메서드가 `static` 메서드인데, `InputView` 를 생성할 필요는 없겠죠?
`private` 생성자를 선언하여 인스턴스화할 수 없는 클래스로 만들어주는 것이 좋겠어요.

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +            if(name.length() > MAX_CAR_NAME_LENGTH) return false;
이름의 길이가 5 이상이라서 입력을 다시 받는 경우에는 왜 입력을 다시 받는지 사용자에게 알려주어야 합니다.

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +        int tryCount = scanner.nextInt();
만약 `tryCount` 가 0이나 음수라면 어떨까요?

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/ResultView.java
> +        List<String> winners = getWinners(racingCars);
View 의 역할은 단순히 '출력'만 하는 곳인데, 여기서 `getWinner` 라는 우승자를 찾는 '도메인 로직'이 존재합니다. `getWinner` 는 View 에 있어야 하는 역할이 아니겠죠. 그렇다면 어디에 있어야 할까요? 근거도 함께 댓글로 달아주세요.

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/ResultView.java
> +        }
String.repeat 메서드를 사용하면 훨씬 쉽게 구현할 수 있습니다.

2024-08-04 09:57 UTC, Cyma-s commented on src/main/java/view/ResultView.java
> +    private static void addWinner(List<String> winners, Car car, int maxDistance){
마찬가지로 우승자를 가려내는 '도메인 로직'이죠

2024-08-04 09:57 UTC, Cyma-s commented on src/test/java/RacingGameTest.java
> +    }
아마 제가 전달드린 글들을 읽어보셨겠지만, 생각해봤을 때 너무나도 당연한 테스트는 굳이 하지 않아도 됩니다.
이상한 입력이 들어왔을 때도 프로그램이 제대로 동작하는지 '검증하기 위해' 테스트를 한다고 생각해주셔야 합니다.
이번 리뷰 반영 때는 필요하다고 생각되는 부분의 단위 테스트를 '모두 작성'해 주세요.

2024-08-07 13:24 UTC, hayeounglee commented on src/main/java/RacingMain.java
> +        final var tryCount = InputView.getTryCount();
<공부한 내용>
- `var`
    - 타입이 길어 읽기에 불편할 때 var을 사용함으로써 읽기 쉬운 코드를 작성할 수 있다
    - 사용가능한 곳은 지역변수로 한정 (전역변수X)
    - 반드시 초기화해야함
- 전역변수: 함수 밖에 선언 → class전체에서 사용가능
- 지역변수: 함수 속에 선언 → 함수 속에서만 사용가능

<결론>
사용한 이유: 타입을 적지 않음로써 읽기 쉽게 함

2024-08-07 14:05 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
공부한 내용)
static메서드에는 인스턴스 변수를 사용할 수 없음.

결론)
getCarNames()와 getTryCount() 는 static 메서드임.
static 메서드는 인스턴스 변수를 사용할 수 없기에 scanner를 static으로 선언함.

2024-08-07 14:39 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +        int tryCount = scanner.nextInt();
`tryCount`가 0이하일 떄는 다시 입력하도록 해야 합니다.
이를 구현하기 위해 `tryCount > 0`일 때 `tryCount`를 리턴하도록 했습니다.

질문)
try-catch 문을 꼭 사용해야 할까요?

2024-08-07 14:51 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +            if(name.length() > MAX_CAR_NAME_LENGTH) return false;
넵 수정했습니닷

질문)
이름이 5자 이하면 Valid한 이름인데
그럼 이름이 공백일 때도 가능하다는 건가요?
(일단 공백일 때는 재입력 하도록 코드를 수정한 상태입니다)

2024-08-08 15:18 UTC, hayeounglee commented on src/main/java/view/ResultView.java
> +        List<String> winners = getWinners(racingCars);
View가 아니라 RacingCar에 있어야 한다고 생각합니다.
왜냐하면~

2024-08-08 15:59 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +public class InputView {
맞습니다, InputView를 생성할 필요는 없습니다.
그러나 InputView 클래스를 private으로 선언하게 되면 
RacingMain.java에서 InputView 클래스를 인식할 수 없을 것 같다는 생각이 듭니닷

2024-08-10 06:14 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    public static List<String> getCarNames(){
결론)
현재 작성한 코드 기준 static을 썼을 때 장단점은 이렇게 정리할 수 있습니다.

장점: 인스턴스를 생성하지 않고도 static 자원에 접근이 가능합니다. 따라서 RacingMain.java 코드가 간결해집니다.
단점: 추후에 인터페이스를 구현하게 될 떄 Static으로 선언된 메서드는 사용할 수 없습니다.

(static을 사용하면 어디서든 외부에서 접근이 가능하여 수정할 수 있는 단점이 있지만,
현재 코드에서는 이런 문제가 단점이라고 할 수 없습니다. 왜냐하면 MAX_CAR_NAME_LENGTH은 final 변수이기 때문입니다.)

2024-08-10 07:23 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    public static List<String> getCarNames(){
공부한 내용)
https://medium.com/@ehd8266/static%EC%9D%98-%EC%98%AC%EB%B0%94%EB%A5%B8-%EC%82%AC%EC%9A%A9%EB%B2%95%EC%9D%80-d95a7b91c6f8
- 장점)
    - **GC 오버헤드를 줄여줌 → 성능을 향상**
        - EX) 공통으로 사용해야하는 메서드를 10,000번 호출할 때
            - Static 사용하면 → Heap 영역에 생성 및 해제를 할 필요없이 사용가능. Good~
    - **코드를 간결하게 작성**
        - new 키워드를 통해 객체 생성없이 호출 가능
    - **어디서든 접근이 가능**
        - 어느 클래스든 static 변수나 메서드를 불러와 사용할 수 있음
- 단점)
    - **무분별한 Static의 사용은 Memory Leak의 원인이 됨**
        - static은 프로그램이 시작될 때 → 메모리를 할당받고, 프로그램을 종료 시 →  메모리를 해제함
        - GC가 메모리 해제를 하지 못함 → 메모리 부족
    - **객체지향적이지 않음**
        - Static을 사용할 경우 어디서든 접근이 가능 → 캡슐화의 원칙을 위배됨
        - 캡슐화: 한 객체가 가지고 있는 데이터들은 외부에서 함부로 접근하여 수정할 수 없도록 하는 원칙
    - **Static은 재사용성이 떨어짐**
        - ****Static으로 선언된 메소드 → Interface를 구현하는데 사용될 수 없음
        - interface
            - 규제. 객체가 특정한 인터페이스를 사용한다면 그 객체는 반드시 인터페이스의 메서드를 구현해야 함
            - 사용하는 이유: class가 어떠한 메서드,멤버를 가지고 있어야 하는지 알려주는 명세서 같은 역할. 협업할 때 사용.

2024-08-11 01:43 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +        return racingCars;
공부한 내용)
- **방어적 복사**
    - 원본과의 참조를 끊은 복사본을 만들어 사용하는 방식
    - 원치 않는 외부 데이터 조작으로부터 내부 구조를 보호하기 위해 사용
    - Defensive copy로 바꾸는 상황
    1️⃣ field를 초기화하기 위해 변경 가능한 object를 받을 때
    2️⃣ 변경가능한 field를 반환할 때

2024-08-11 15:36 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +        return racingCars;
RacingGame 인스턴스를 한번 생성하였는데 방어적 복사를 꼭 해야하나요..?

2024-08-11 15:48 UTC, hayeounglee commented
좋은 리뷰 덕분에 많은 것을 생각해 볼 수 있었습니다 감사합니다 :)

제가 리뷰 답변 하는데 1주일이나 걸렸던데 
분발해서 남은 기간 동안 더 많은 것을 배워 나가겠습니다 😅

2024-08-15 02:22 UTC, Cyma-s commented on src/main/java/RacingMain.java
> +        final var tryCount = InputView.getTryCount();
var 를 사용하는 것은 좋은데 일관적으로 사용해야 하고, 제네릭 같이 명백하지 않은 타입이나 다형성을 사용해야 할 때는 타입을 명시해야 한다는 걸 알아두세요~!

2024-08-15 03:08 UTC, Cyma-s requested changes
이번 주가 바빠서 리뷰가 조금 늦었네요. 죄송합니다. 테스트를 여러 가지 추가해주신 것 확인했습니다.

제가 코멘트로 남긴 질문에 답변을 남기실 때는 어떤 정보를 알아봤는지 적는 것도 좋지만, 배운 그 내용을 바탕으로 나는 이렇게 생각한다! 라는 의견을 듣고 싶은 거에요. (근거 링크도 필요 없습니다)

절대 블로그에서, 책에서 이렇게 말한다고 다 믿지 마세요. 직접 해보시고 느껴보세요. 지금까지 블로그로 공부하셨던 내용들은 모두 마음에 와닿으셨나요? 이해가 안 되는 내용들이 분명히 있었을 텐데 (특히 방어적 복사가 왜 필요한지, static 이 왜 객체지향적이지 않은지 등) 그런 부분에 대한 질문이 부재한 것이 아쉽습니다. 지식은 다른 사람들이 알고 있는 내용을 답습하는 것이 아니라 내가 머리로, 마음으로 이해해야 진정으로 알 수 있게 돼요. 뭐든 편하게 물어봐도 되니까 지금보다 조금 더 이해가 안 되는 게 많았으면 합니다.

말이 길었네요. 코멘트 확인해주시고 반영해주세요~

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +    private List<Car> racingCars;
racingCars 를 final 로 만들면 안 될까요?

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return racingCars;
요 부분을 stream 을 사용해서 개선해봅시다. Stream 에 대해 알아보시고 코드 리팩토링해주세요!

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +            if ((isMovable(randomInt))) racingCars.get(i).incrementDistance();
{} 넣어주세요!!!!!

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +    public static boolean isMovable(int randomInt) {
static 이 붙은 이유가 있을까요?

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +    public static boolean isMovable(int randomInt) {
`isMovable` 을 담당해야 하는 주체가 RacingGame 일까요?

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return racingCars;
방어적복사는 객체 내부 컬렉션을 getter 로 받아올 때 처리해주어야 합니다.

먼저 객체가 여러 개 만들어지는 것과는 관련이 없습니다. 방어적 복사에서 중요한 점은 한 객체의 컬렉션 필드를 외부에서 수정하지 못하도록 하는 것이에요. 
지금 상황에서 방어적 복사를 적용하지 않으면, RacingGame 에서 cars 를 조회한 뒤에 add, remove 등이 자유롭게 이루어질 수 있어요. 그러면 cars 의 변경 사항을 추적하기가 훨씬 힘들어지겠죠. 

방어적 복사를 적용하게 되면 실제 RacingGame 의 cars 객체를 '직접' 외부에 전달하지 않고 cars 객체의 복사본을 외부에 전달하기 때문에 외부에서 어떤 수정을 하더라도 RacingGame 의 cars 에는 영향이 없어요. 그렇다면 훨씬 안정적인 프로그램을 만들 수 있겠죠.

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +    public static List<String> getWinners(List<Car> racingCars) {
아래 메서드들도 다 static 으로 선언되어 있네요? 이유가 뭘까요?

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return winners;
왜 Winner 는 String 으로 리턴하나요? 가능하다면 리턴값이나 매개변수는 도메인 객체로 주고받는 것이 좋습니다. 특히나 RacingGame 이 일종의 서비스 역할을 할 때는 더더욱이요.

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return maxDistance;
마찬가지로 stream 으로 리팩토링 해주세요

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +    }
Stream 으로 가능합니다

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +public class InputView {
아뇨 InputView 를 private 클래스로 만들라는 뜻이 아니라 InputView 의 '생성자'를 private 으로 하라는 뜻이에요. 

Private 생성자가 어떤 의미를 갖는지 알아보시고 반드시 '생각을 정리해서' 댓글을 올려주세요.

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
전후 관계가 잘못되었어요. Scanner 를 static 으로 쓰실 거면 static 으로 사용했을 때 문제가 없는지, static 변수로 사용해야 하는지 먼저 알아봤어야 해요. 
다른 static 메서드에서 해당 변수를 사용해야 한다고 변수가 static 이 된다면, 반대로 변수가 static 이 아니기 때문에 메서드를 비 static 메서드로 만드는 것도 고려해보셔야 합니다. 둘 다 고민해보시고 고민 과정을 댓글로 남겨주세요.

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    public static List<String> getCarNames(){
객체 지향은 객체에게 메시지를 보내는 거에요. 어떤 객체의 정보를 외부에서 자유롭게 꺼내쓰는것이 아니라, 객체 스스로 정보를 사용해서 행동히는 것을 원하는 거죠. 그러나 static 은 외부에서 변수에 자유롭게 접근하여 수정할 수 있기 때문에 객체지향과는 멀다고 할 수 있어요. 

특히 **메모리를 절약하기 위햐** static 을 사용하지는 않길 바랍니다. static 은 클래스에 단 하나만 존재하기 때문에 동시성 문제가 발생할 수 있어요. 자원 경쟁이 일어날 수도 있고요. 최대한 static 객체변수 사용은 자제해주세요.

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +            List<String> carNames = new ArrayList<>(Arrays.asList(input.split(",")));
왜 asList 로 변환항 값을 ArrayList 로 한 번 더 래핑하셨나요?

2024-08-15 03:08 UTC, Cyma-s commented on src/main/java/view/ResultView.java
> +        List<String> winners = domain.RacingGame.getWinners(racingCars);
View 에서 Service 레이어를 '호출' 하네요? 아주 큰일입니다. View 는 데이터 입출력만 담당할 뿐, 그 외의 어떤 도메인과도 연관되어서는 안 됩니다. 지금은 아예 도메인 패키지가 이름에 나와있네요.

2024-08-15 03:08 UTC, Cyma-s commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
이렇게 ByteArrayInputStream 으로 귀찮게 작성해야 하는 이유는 InputView 의 Scanner 가 static 이기 때문입니다. 테스트하기 어려워졌죠?

2024-08-15 03:08 UTC, Cyma-s commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
만약 나타내는 글자가 바뀐다면 테스트가 다 변경되어야겠네요? 어떻게 고칠 수 있을까요?

2024-08-18 05:34 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    public static List<String> getCarNames(){
넵 static 사용을 최소한으로 줄이는 코드로 변경했습니다.

그럼 static 사용을 최대한 지양해야하면 보통 언제 사용하는지 궁금합니다.  
인스턴스들이 공통적으로 값을 유지해야할 때일까요?

2024-08-18 06:50 UTC, hayeounglee commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
public static final로 문자열을 선언하는걸로 수정했습니다

2024-08-18 08:14 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +            if ((isMovable(randomInt))) racingCars.get(i).incrementDistance();
이것도 들여쓰기 1이하로 해야 하나요?
들여쓰기 2로 해도 복잡해보이지 않아서 여쭤봅니닷

2024-08-18 08:14 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +    private List<Car> racingCars;
된다고 생각합니다.
왜냐하면 RacingMain을 보면 정상적인 입력을 받은 후 이를 RacingGame에 넘겨주고 있기에
사용자가 caNames를 재입력하여 racingCars가 수정되는 경우는 없기 때문입니다.

2024-08-18 08:14 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +    public static boolean isMovable(int randomInt) {
자동차의 행동과 연관이 있기 때문에 Car이 될 수 있을 것 같지만
메서드의 주체에 대한 판단이 잘 서지 않네요.

그래서 각 class의 역할을 정의해봤습니다.

Car: car의 상태와 행동을 관리
RacingGame: game이 시작할때 초기화, 게임 진행, 게임 winner 계산하기

2024-08-18 14:58 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +    public static boolean isMovable(int randomInt) {
isMovable을 Car 옮긴 후에도 static을 쓴 이유는
RacingGame 의 playOneRound메서드에서 객체생성없이 사용하기 위해서입니다.

-> 수정)
테스트를 하기 위해 static을 붙이는건 잘못된 방향
strategy로 옮겨야 함

2024-08-18 14:58 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +    public static List<String> getWinners(List<Car> racingCars) {
Test 코드 작성할 때
객체생성없이 사용하기 위해서였으나 이는 잘못되었으므로

static을 삭제 했습니다.

2024-08-18 14:58 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +public class InputView {
앗 제가 잘못 이해했네요 이제 생성자의 뜻 이해했습니다. 

현재 수정된 InputView는 메서드가 static이 아니지만
전에 작성된 InputView의 경우 말해주신대로 private 생성자를 만들어줘야 합니다.

만약에 private 생성자가 없는 상태에서 객체를 생성하게 되는 일이 생기면 디폴트 생성자가 만들어지며 객체가 생성됩니다.
따라서 객체를 만들 목적의 클래스가 아니고 객체 생성을 막기 위해서 private 생성자를 만들어야 합니다.

2024-08-18 14:58 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +            List<String> carNames = new ArrayList<>(Arrays.asList(input.split(",")));
`split()` 메서드는 String array를 리턴합니다.
따라서 collection인 List로 반환하기 위해 Arrays.asList 으로 래핑했습니다.

그런데 ArrayList으로 한번 더 래핑한 이유는 
ArrayList 클래스를 통해 add, remove와 같은 메서드를 사용할 수 있기 때문입니다.

그러나 현재 carNames에 추가/삭제 기능이 필요 없으므로 
ArrayList로 한 번더 래핑할 이유가 없습니다. 삭제하겠습니다.

2024-08-18 14:58 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +            List<String> carNames = new ArrayList<>(Arrays.asList(input.split(",")));
궁금한게 있습니다.
만약 Array를 -> ArrayList로 변환하고 싶으면 아래와 같이 하면 될 것 같은데
`List<String> carNames = new ArrayList<>(input.split(","));`

왜 Arrays.asList()를 사용해서 Array를 List로 바꿔준 다음 ->  ArrayList로 변환하는 건가요? 🤔

2024-08-19 03:32 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +        return racingCars;
방어적 복사의 필요성을 이해했습니다.

궁금한 점은 방어적 복사와 깊은 복사의 차이는 무엇인가요?

자바의 copy방법을 찾아보던 중 깊은 복사, 얕은 복사가 있더라고요,
위의 예제에서 방어적 복사가 List의 참조값이 아닌 원본 List와 독립적인 List를 리턴한다는 점에서
깊은 복사와 비슷한 것 같다는 생각을 했습니다.

2024-08-21 04:43 UTC, hayeounglee commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
ByteArrayInputStream으로 작성하게 된 이유가 Scanner가 static이라서 라는 부분을 더 설명해 주실 수 있을까요?

제가 ByteArrayInputStream을 사용한 이유는
큰솔에 입력하는 것 없이 InputStream을 직접 만들기 위함 입니다. 
그래서 view.InputView.getCarNames(); 가 실행되면
미리 만들어 놓은 테스트 데이터가 들어가도록 위함입니다.

그래서 scanner가 static과 무슨 연관이 있는지 잘 모르겠습니닷

2024-08-21 07:06 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
공부하다가 궁금한게 생겨 물어봅니닷

 **scanner 인스턴스는 한번만 선언되는 것이 좋은 이유가 무엇인가요?**
찾아보니 그 이유가 두개의 Scanner인스턴스가 같은 input source를 읽으려고 시도하면 하나가 steal 할 수 있기 때문이라고 합니다.
이게 무슨 상황인지 이해가 가지 않습니다.

2024-08-21 07:06 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
위의 내용이 맞다는 전제하에
하나의 scanner 인스턴스만 생성하는 방법에 대해 알아봤습니다.

1.  main()함수에 scanner객체 만들기
-> parameter로 scanner전달하기

2. mani함수가 있는 Main 클래스에 필드값으로 scanner 객체 만들기

2. input class를 만들어 이 class 내에서  scanner 객체 만들기
-> 이때 static으로 scanner선언하기

2024-08-21 07:06 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
이떄 3번 째의 경우 singleton 패턴을 사용하고 있으며 
이는 thread safe하지 않습니다.

왜냐하면,
예를 들어 Scanner를 반환하는 getInstance를 두 개의 thread가 동시에 호출하면 
sc가 null로 인식되어 두 개의 Scanner 가 생성될 수 있습니다.

2024-08-21 07:06 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
따라서 Scanner 인스턴스가 하나만 생성되는게 좋다면
1,2방법을 사용하거나 동시성이 가능하다록 3번을 수정한다음 사용할 것 같습니다.

2024-08-21 07:06 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
현재 제가 작성한 코드의 문제점은
InputVIew 객체를 생성할 때마다 Scanner 객체가 static으로 여러개 만들어 질 수 있다는 것입니다. 

따라서 피드백을 듣고 이를 수정하려 합니닷

2024-08-21 13:56 UTC, hayeounglee commented on src/main/java/view/ResultView.java
> +        List<String> winners = domain.RacingGame.getWinners(racingCars);
domain에 있는 getWinners의 위치를 수정했습니다

2024-08-27 12:39 UTC, Cyma-s requested changes
많은 개선이 있었네요. 답글로 달아주신 질문에도 답변 남겼습니다. 시간되실 때 확인해주세요 :)

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/RacingMain.java
> +        ResultView resultView = new ResultView();
여기도 `final` 로 선언되면 좋을 것 같아요

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/domain/Car.java
> +    private static final int MOVE_THRESHOLD = 4;
상수와 변수 사이에는 공백을 띄워주세요 :)

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/domain/Car.java
> +    }
해당 메서드는 메서드가 사용되는 곳에서 가장 가까운 곳에 위치해야 합니다. 이유는 가독성 때문이에요. 관련된 메서드가 사용된 메서드 주변에서 발견되는 게 코드를 읽을 때 더 좋겠죠? 지금 경우에는 생성자 밑에 위치하면 됩니다.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +            int number = numberGenerator.generator();
`generator` 는 명사라서 `generate` 가 더 좋아보여요

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +            if ((Car.isMovable(number))) {
필요 없는 괄호는 제거해주세요!

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return List.copyOf(winners);
여기서 `winners` 는 copyOf 를 사용해서 리턴하지 않아도 되는데요, 이유가 무엇일지 알아보고 댓글로 알려주시겠어요?

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +                .orElse(0);
기본값을 0으로 둔 것 좋습니다 👍🏻

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/strategy/FixedNumberGenerator.java
> +    }
사이에는 공백!

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/strategy/FixedNumberGenerator.java
> +        this.numbers = new ArrayList<>(numbers);
음 이렇게 해줄 수도 있죠 👍🏻

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/strategy/FixedNumberGenerator.java
> +    private final List<Integer> numbers;
메서드와 변수 사이에는 공백을 넣어주세요

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/strategy/RandomNumberGenerator.java
> +    private Random random;
`final` 을 붙이지 않은 이유가 있을까요?

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +public class InputView {
맞습니다 util 클래스의 경우에는 `static` 메서드를 사용할 때 객체가 만들어질 필요가 없죠. 그래서 외부에서 인스턴스를 생성할 수 없도록 따로 `private` 생성자를 만들어 주는 것이 좋습니다. 다른 동료 개발자의 실수를 막아줄 수 있겠죠.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private Scanner scanner = new Scanner(System.in);
`final`!

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +        }
한 번 실행하고 return 할 거면 while 문이 필요 없지 않을까요?

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +            }
음수는 안 된다는 규칙은 `InputView` 에 존재해도 괜찮을까요?

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/ResultView.java
> +    public void printResult(RacingGame racingGame) {
굳이 `racingGame` 을 인자로 보내지 않고, 지금 getter 로 가져다 쓰고 있는 값들을 매개변수로 넣어주는 것이 좋습니다. 이렇게 매개변수로 중요한 서비스 객체가 주어지게 되면 `ResultView` 와 `RacingGame` 사이에 의존이 발생하는 거라서요.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/ResultView.java
> +    }
여기서도 필요한 게 distance, name 만이라면 `Car` 객체를 굳이 입력받을 필요 없이 String, int 값을 입력받는 것이 낫습니다.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return racingCars;
깊은 복사는 얕은 복사와 구별하기 위해 만들어진 단어입니다. 
방어적 복사는 외부에서 컬렉션 객체를 수정할 수 없도록 수정이 불가능한 컬렉션을 리턴하거나, 내부 객체에 영향을 주지 못하는 '깊은 복사' 를 사용하여 내부 컬렉션 객체를 외부에 리턴하는 것입니다.

사용되는 용도는 비슷할 수 있으나, 각각의 단어가 사용되는 맥락은 많이 다릅니다.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
같은 input source 라는 것은 같은 입력 장치로부터 입력을 받을 때를 뜻합니다. 예를 들어 노트북 키보드로 값을 입력하는 것도 하나의 입력 소스가 될 수 있죠. 
하나의 입력 소스에 대해 여러 개의 Scanner 가 선언되면 두 개의 객체가 동시에 입력을 받고 싶을 때, 하나의 입력 소스에 대한 경쟁을 해야 하니 동시성 문제가 발생할 수 있겠죠. 저는 개인적으로 Scanner 를 여러 개 선언하게 되면 어떤 Scanner 를 써야 하는지 혼동이 생기기 때문에 동일한 입력 소스에 대한 Scanner 를 여러 개 만들지 않는 편입니다.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
2번 방법은 3번과 동일하게 Scanner 를 static 으로 선언해야 합니다. main 함수는 static 함수이기 때문에 static 변수만 접근할 수 있기 때문이죠.
3번 방법을 사용할 때 문제점은 Singleton 을 사용하여 동시성 문제가 발생할 수 있는 것은 맞으나, thread safe 하지 않다는 것은 틀립니다. 제안해주신 방법을 사용한다면 thread safe 하지 않은 Singleton 이 만들어질 수 있으나, Singleton Holder 방법을 사용하게 되면 thread safe 하게 Singleton 을 생성할 수 있습니다.

고민하셔야 하는 부분은 그 부분이 아니라, '`InputView` 가 동시성을 고려해야 하는가?', '`InputView` 를 유틸 클래스로 만들어야 하는가 아니면 인스턴스화 가능한 객체로 만들어야 하는가?` 같은 부분입니다. 이 부분에 대해서는 어떻게 생각하시나요?

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
> 현재 제가 작성한 코드의 문제점은 InputVIew 객체를 생성할 때마다 Scanner 객체가 static으로 여러개 만들어 질 수 있다는 것입니다.
> 
> 따라서 피드백을 듣고 이를 수정하려 합니닷

제가 제대로 이해했는지 모르겠는데 객체를 생성할 때마다 Scanner 객체가 생성되어 여러 개 만들어질 수 있다는 뜻인가요?

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    public static List<String> getCarNames(){
보통 객체 필드 값과 소통하지는 않는데, 해당 클래스에서 맡아야 하는 책임의 기능이면 static 을 사용하는 경우가 많습니다.
그 대표적인 예시가 바로 유틸 클래스입니다. Math.max(10, 20) 같은 함수는 수학과 관련은 있으나 굳이 Math 객체가 여러 개 생성될 필요는 없죠. `Math` 객체의 메서드들이 모두 단순한 기능만 제공하기 때문입니다.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +        int tryCount = scanner.nextInt();
try catch 문을 사용하지 않으면 사용자에게 아무런 피드백 없이 예외가 발생했을 때 프로그램이 꺼집니다. 그런 경우에 사용자는 프로그램에 문제가 발생했다고 생각하겠죠. try-catch 를 사용하면 개발자가 예상할 수 있는 예외가 발생했을 때 바로 프로그램을 종료시키는 대신, 예외에 대한 설명을 해주고 그에 대처하는 행동을 수행할 수 있죠. 훨씬 할 수 있는 행동의 폭이 넓습니다.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +            if ((isMovable(randomInt))) racingCars.get(i).incrementDistance();
'들여쓰기 1 이하로 해야 한다'는 이 미션의 '규칙'이기 때문에 지금은 가독성과 무관하게 따르셔야 합니다.

2024-08-27 12:39 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +            List<String> carNames = new ArrayList<>(Arrays.asList(input.split(",")));
`ArrayList` 의 생성자에는 매개변수로 Array 를 받는 생성자가 없기 때문입니다.

2024-08-27 12:39 UTC, Cyma-s commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
`Scanner` 가 static 으로 클래스가 생성될 때 만들어지는데, 이때 입력 소스는 `System.in` 으로 고정되어 있습니다. `ByteArrayInputStream` 을 사용한 이유는 'InputStream 을 직접 만들기 위해서' 이죠. 클래스가 생성된 이후로 이미 고정된 InputStream 으로 만들어진 Scanner 를 변경시킬 수는 없으니까요.
그러면 Scanner 를 static 으로 선언하지 않고 외부에서 전달할 수 있었다면 어떨까요?

2024-08-29 12:43 UTC, hayeounglee commented on src/main/java/RacingMain.java
> +        ResultView resultView = new ResultView();
class 의 경우 final 키워드는 
한 번만 할당할 수 있는 엔터티를 정의하거나(불변을 보장하는 것이 아니라)
상속할 수 없게하기 위해 사용된다는데

여기서도 그런의미로 사용하라는 건가요? 🤔

2024-08-29 13:15 UTC, hayeounglee commented on src/main/java/strategy/RandomNumberGenerator.java
> +    private Random random;
final을 꼭 사용해야할 이유를 모르겠습니다..🤔(안썼을 때 발생하는 문제가 무엇이 있나요?)

2024-08-29 13:30 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private Scanner scanner = new Scanner(System.in);
final을 쓰지 않았을 때 발생하는 문제가 무엇이 있나요?🤔

2024-08-29 14:32 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +            }
이런 로직은 InputView에 존재하는 것보다 다른 곳에 위치하는 것이 좋은 것 같아
수정했습니닷

2024-08-29 14:51 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +        return List.copyOf(winners);
결과를 프린트할 때만 getWinners 함수를 호출하기 때문에 
꼭 방어적 복사를 할 필요가 없다고 생각합니닷

2024-08-29 15:01 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +            if ((isMovable(randomInt))) racingCars.get(i).incrementDistance();
넵 stream을 사용해서 수정했습니닷

2024-08-30 06:29 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
그런 뜻으로 말한거긴 한데 수정 사항이 있어 다시 말하겠습니다.
InputView 객체들이 새로 생길 때마다  static 영역에 있는 Scanner 객체 하나를 공유합니다.

2024-08-30 06:30 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
>  'InputView 가 동시성을 고려해야 하는가?'

InputView가 동시성을 고려해야 되는가에 대한 질문을 접했을 때 궁금한게 생겼습니다.
동시성 문제는 여러 쓰레드가 같은 자원에 동시 접근할 때 발생하는데
그럼 여기서 ‘여러 쓰레드가 동시에 접근하는 상황’이 현재 코드에서 발생하는지 궁금합니다. 
발생한다면 어떤 상황일 때 인지 궁금합니다.

2024-08-30 07:00 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
> 'InputView 를 유틸 클래스로 만들어야 하는가 아니면 인스턴스화 가능한 객체로 만들어야 하는가?` 

유틸 클래스로 만들거나 한번만 인스턴스화 가능한 객체로 만드는 방법 모두
scanner를 static으로 선언해야 합니다. 

scanner를 static으로 선언하는 경우 InputView은 유틸 클래스가 됩니다. 
왜냐하면 모든 필드들이 scanner를 사용하기 때문에 모든 필드들이 static이 되기 때문입니다.

2024-08-30 07:05 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
궁금한 점은 싱글 톤 패턴으로 InputView를 만들 때 
왜 scanner를 static으로 선언하는 건가요? 

`import java.util.Scanner;

public class ScannerSingleton {
    private static Scanner sc = null;

    private ScannerSingleton() {
        sc = new Scanner(System.in);

    }

    public static Scanner getInstance() {
        if (sc == null) {
            synchronized(ScannerSingleton.class) {
                if (sc == null)
                    sc = new ScannerSingleton();
            }
        }

    }
}`

2024-08-30 07:19 UTC, hayeounglee commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
InputView가 매개변수 scanner 객체를 받으면 scanner를 static으로 선언할 필요가 없어집니다.

그럼 static으로 선언하지 않을 경우 input 테스트를 한다면 ByteArrayInputStream이 아니라 어떻게 해야 하나요?  🤔

2024-08-30 10:03 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
싱글톤을 선언할 때 중요한 것은 '싱글톤 객체가 단 한 번 생성되어야 한다' 라는 것입니다. 
`ScannerSingleton` 을 싱글톤으로 만들려면, `ScannerSingleton` 는 단 한 번 생성되고 포함된 필드들도 반드시 단 한 번 초기화되어야 합니다.
외부에서 `ScannerSingleton` 객체를 생성할 수 없게 하기 위해 private 생성자를 만들었습니다. 이런 경우에는 클래스 내부에서 싱글톤 객체를 생성할 수 밖에 없죠. 그러면 해당 클래스에서 클래스의 인스턴스를 딱 한 번 만들어 주어야 하는 상황이 되기 때문에 static 메서드를 사용하여 인스턴스를 생성하게 되는 것입니다. 또한 static 메서드 내부에서는 static 필드만 사용할 수 있기 때문에, `Scanner` 객체도 static 필드로 선언해야 합니다.

무엇보다 `ScannerSingleton` 을 싱글톤으로 만들고자 한다면 **`ScannerSingleton` 객체를 필드로 가지고 있어야 합니다.** 또한 현재 코드에서는 `getInstance` 메서드에서 `Scanner` 를 아예 리턴하지 않고, sc 에 `ScannerSingleton` 을 선언하는 잘못된 코드가 존재합니다. 

다음 코드도 잘못된 부분이 있습니다.

```java
private ScannerSingleton() {
        sc = new Scanner(System.in);
    }
```

싱글톤 패턴은 특정 클래스의 인스턴스를 단 하나만 생성하고, 그 인스턴스에 대한 전역 접근점인 static 메서드를 제공하는 것입니다. private 생성자는 외부에서 객체를 직접 생성하는 것을 막기 위해 사용하는데, 인스턴스 초기화를 생성자 내부에 포함시키는 경우에는 생성자를 호출해야만 초기화 코드가 실행됩니다. 이 경우, 싱글톤의 의도와 다르게 동작할 수 있습니다.
또한 private 생성자 내부에서 초기화를 하게 되면 클래스의 정적 필드가 초기화되는 시점을 정확하게 제어할 수 없습니다. static 메서드가 호출되기 전에 private 생성자가 호출될 수도 있어 불필요한 초기화가 이루어질 수도 있습니다.

결론적으로, 첫 번째 `getInstance` 호출 시에 `Scanner` 가 초기화되는 로직의 일관성을 보장하려면 **private 생성자 내부에 초기화 로직이 존재하지 않아야** 합니다.

2024-08-30 10:05 UTC, Cyma-s commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
좋은 고민입니다. 
한 번 이런 관점에서 생각해보죠. InputView 의 테스트는 왜 필요한가요? 그리고 무엇을 테스트하는 것인가요?

2024-08-30 10:09 UTC, Cyma-s commented on src/main/java/RacingMain.java
> +        ResultView resultView = new ResultView();
그런 의미로 사용하라는 의미느 아니었습니다. 일반적으로 코드에서 inputview, resultView 에 새로운 객체를 초기화해서 사용하지 않도록, 변수를 선언할 때는 습관적으로 final 을 붙이는 것이 좋습니다. 이렇게 변수에 값을 재할당할 수 없도록 컴파일 시점에서 (final로) 막아두는 것이 좋습니다.

2024-08-30 10:10 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return List.copyOf(winners);
의도한 바는 그 부분이 아니긴 합니다 😅

stream 의 collect 함수를 사용하여 생성한 리스트는 자동으로 불변 리스트로 만들어지기 때문에 굳이 `copyOf` 를 사용하여 방어적 복사를 해줄 필요가 없습니다. 애초부터 불변이니까요.

2024-08-30 10:11 UTC, Cyma-s commented on src/main/java/strategy/RandomNumberGenerator.java
> +    private Random random;
항상 다른 개발자를 염두에 두고 개발하셔야 합니다. 동료 개발자가 random 함수를 재할당할 수 있는 **위험**을 굳이 내버려둘 필요는 없겠죠.

2024-08-30 10:12 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private Scanner scanner = new Scanner(System.in);
이후 코드에서 scanner 가 불변한다는 보장을 할 수 없습니다. 해당 코드에서는 제가 `InputView` 의 아무 메서드에서 scanner 를 재할당하더라도 저를 막을 수 없죠.

2024-08-30 11:54 UTC, Cyma-s requested changes
마지막 RC 입니다. **강조했던 컨벤션 지켜서 다시 올려주세요**

2024-08-30 11:54 UTC, Cyma-s commented on src/main/java/domain/Car.java
> +            throw new IllegalArgumentException(NAME_VALIDATION_ERROR_2);
의미있는 숫자가 아니라면 숫자는 상수에 적지 않는 것이 좋습니다.

2024-08-30 11:54 UTC, Cyma-s commented on src/main/java/domain/Car.java
> +            throw new IllegalArgumentException(NAME_VALIDATION_ERROR_2);
그리고 보통 이런 에러 메시지 같은 경우는 상수로 처리하지 않기도 해요!

2024-08-30 11:54 UTC, Cyma-s commented on src/main/java/domain/Car.java
> +    }
보통 제일 관련 없는 getter 는 클래스 맨 아래에 선언하곤 합니다.

2024-08-30 11:54 UTC, Cyma-s commented on src/main/java/domain/RacingGame.java
> +        return winners;
이렇게 짧게 작성해도 무방합니다 :)

```suggestion
        return racingCars.stream()
                .filter(car -> car.getDistance() == maxDistance)
                .map(Car::getName)
                .collect(Collectors.toList());
```

2024-08-30 11:54 UTC, Cyma-s commented on src/main/java/strategy/RandomNumberGenerator.java
> +    private static final int RANDOM_BOUND = 10;
static 변수와 변수 순서가 바뀌었어요.

2024-08-30 11:54 UTC, Cyma-s commented on src/main/java/strategy/RandomNumberGenerator.java
> +    @Override
제발 공백 띄워주세요.

2024-08-30 11:54 UTC, Cyma-s commented on src/main/java/view/InputView.java
> +    private final Scanner scanner = new Scanner(System.in);
리뷰 제출하기 전에 이전 리뷰 컨벤션 반드시 필독하고 제출해주세요. 반복되는 피드백인 것 같습니다.

2024-09-05 01:45 UTC, hayeounglee commented
피드백 감사합니다 
이번주에 완료하도록 하겠습니다!!

2024-09-08 06:33 UTC, hayeounglee commented on src/main/java/domain/RacingGame.java
> +        return List.copyOf(winners);
그렇군요 감사합니다 :)

2024-09-08 13:05 UTC, hayeounglee commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
그렇네요 이상한 싱글톤 예제였네요😅 자세한 설명 감사합니다 이해했습니닷!

2024-09-08 13:56 UTC, hayeounglee commented on src/main/java/view/InputView.java
>      private final Scanner scanner = new Scanner(System.in);
이렇게 하면 scanner를 static으로 꼭 선언하지 않아도 되는게 맞나요..?🤔

2024-09-08 14:12 UTC, hayeounglee commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
사용자가 잘못된 값을 입력할 때
이를 프로그램이 잘 대응하는지(오류라는 것을 잘 인식하는지) 확인하기 위해 테스트하는 것이 목적입니다.

테스트하는 내용은 Car name 길이가 너무 길지 않는지, tryCount 값이 양수인지 확인하고 있습니다.

2024-09-08 14:20 UTC, hayeounglee commented on src/test/java/RacingGameTest.java
> +        assertTrue(output.contains("이름은 5자를 초과하거나 공백이거나 null 일 수 없습니다."));
이러한 테스트 방법 보다 저번에 배운
잘못된 값이 발생했을 때 IllegalArgumentException 을 통해 예외 처리를 해주고
테스트 케이스를 작성할 때 예외 처리를 하는지 확인하는 코드를 작성하는 것이 더 좋아보입니닷

2024-09-08 14:22 UTC, hayeounglee commented
컨벤션에 좀 더 신경써서 수정했습니다.
질문 한개 작성했는데 시간날 때 한 번 확인해주면 감사하겠습니닷 :)

2024-09-21 00:10 UTC, merged